### PR TITLE
Add better support for static assets

### PR DESCRIPTION
**Pull request by mattdell**
#### What does this PR do?

This pull request addresses feature request #89 and issue #88 by adding support for static file serving for

* static files specified in a static folder
  * The code will check to see if any files exist within a static folder. If so, it will create a resource in API Gateway to proxy all requests from http://mydomain.com/static to the static folder location in S3.
* public files specified in a public folder
  * The code will check to see if any files exist within a public folder. If so, it will create a resource in API Gateway for each file and proxy all requests from http://mydomain.com/mypublicfile.xyz to the public file location in S3.
* NextJS static assets
  * The code will create a resource in API Gateway to proxy all requests from http://mydomain.com/_next to the _next folder location in S3.

This also removes the previous functionality of providing `routes` in serverless.yml.

#### What are the relevant tickets?

* #89 
* #88

#### Where should the reviewer start?

The bulk of the code change is in addCustomStackResources.js

#### How should this be manually tested?

Obviously run the updated unit tests and ensure I've covered all cases.

You'll then want to run this new code to deploy some AWS infrastructure. Without changing anything, you should be able to see a few extra resources in your API Gateway dashboard.

Specifically, you'll want to see an entry for

* `_next/{proxy+}`
* `static/{proxy+}`
* Each public file, i.e. `/manifest.json`

Then ensure you can browse each file once deployed, such as

* https://mydomain.com/_next/static/runtime/main-29fa3c7761b55170bf85.js
* https://mydomain.com/static/manifest.json
* https://mydomain.com/favicon.ico

Screenshot 2019-06-20 at 14 10 05

Also your `<head>` element should only contain relative paths for assets (unless `assetPrefix` is specified in next.config.js).

Screenshot 2019-06-20 at 14 16 03

### CODE REVIEW

**Comment by mattdell** [comment]
I'm not sure what to make of the CI results. Codacy is failing for something I haven't touched. Travis is failing on running the tests. But coveralls is running the tests just fine.

Naturally, all works on my machine. 😄

**Comment by danielcondemarin** [comment]
> I'm not sure what to make of the CI results. Codacy is failing for something I haven't touched. Travis is failing on running the tests. But coveralls is running the tests just fine.
> 
> Naturally, all works on my machine. 😄

I believe is the integration tests failing. I'll have a look tonight, just make sure you enable "Allow edits from maintainers" :)

**Comment by mattdell** [comment]
Screenshot 2019-06-20 at 15 37 55

👍

**Comment by danielcondemarin** [comment]
@mattdell Many thanks for implementing this! Just one thing, I removed the option to configure a custom `static` or `public` folder as next doesn't allow this. 

I'll be looking next at CloudFront support for "production mode". If you don't mind could you post how you use CloudFront in your app, i.e. CF template? I want to get it as close as folks are using in real apps.

**Comment by mattdell** [comment]
> @mattdell Many thanks for implementing this! Just one thing, I removed the option to configure a custom `static` or `public` folder as next doesn't allow this.

I think that's the right decision. As I was writing up the docs I began to think that we shouldn't introduce the option if Next doesn't have it. So, good call.

> I'll be looking next at CloudFront support for "production mode". If you don't mind could you post how you use CloudFront in your app, i.e. CF template? I want to get it as close as folks are using in real apps.

I'll see if I can get back to you about that sometime next week. We're currently in the process of swapping things around with CloudFront.

**Comment by mattdell** [comment]
@danielcondemarin just noticing this error when I try to deploy without a `static` folder:

```
  Error --------------------------------------------------
 
  ENOENT: no such file or directory, scandir 'static'
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
```

Strange as the code looks like it handles that case.

**Comment by danielcondemarin** [comment]
@mattdell I think I've not published the latest code in master yet which I believe handles this. Will publish today 👍

**Pull request merged**
